networks:
    frontend:
        external: true

volumes:
  jenkins_home:

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - frontend
#    ports:
#      - 8080:8080
#      - 50000:50000